# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be06d72ae16fb8cd64f4c07387eb122fb9f79d9f1c200b74633ea79a15d3b327958dc73b2e51c69c7514856a8cb59397fdd0fc5a7e58de59d0612062b7c45fe7

test:
  secret_key_base: 0d457aa450f36dc12d091b882db1ddad5cfbc414cca38d9b4d8609af46a4fed8f62085d16c7a10d594ecd6e2b813c30e8c3680e9c4103d66107eba4bff6e6d58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
